GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5ec60cea640c902d02a50c32

###

POST http://localhost:3000/subscribers 
Content-Type: application/json

{
    "name": "Amazing Person", 
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5ec61f9b32146e310c3713b7

###

PATCH http://localhost:3000/subscribers/5ec61f9b32146e310c3713b7
Content-Type: application/json

{
    "name": "New name"
}